# Generated by Django 2.0 on 2017-12-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20171228_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='age',
            field=models.CharField(default=15, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horse',
            name='number',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
