# Generated by Django 2.0 on 2017-12-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='image',
            field=models.ImageField(default='static/images.jpg', upload_to='static/images'),
        ),
    ]
