# Generated by Django 2.0 on 2017-12-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_horse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='static/images'),
        ),
    ]
