# Generated by Django 2.0 on 2017-12-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20171229_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
