# Generated by Django 2.0 on 2017-12-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.CharField(max_length=556),
        ),
    ]
